### ISSUE TITLE
범용적인 이름

### ISSUE THREAD

**Issue by namenu** [ridibooks/simple-notifier#2]
프로젝트의 이름은 viewer-notification 이지만, 범용적으로 사용할 수 있어 보입니다.
우리와 비슷한 요구사항을 지닌 어떤 곳에서도 쓰일 수 있을만한 프로젝트이니까요.

그래서 이름도 범용적이었으면 좋겠습니다. 어떻게 생각하시나요?

@kyungmi @freekering

**Comment by freekering** [comment]
동의합니다. app-notification-manager 정도가 좋을꺼 같은데 넘 기네요.

**Comment by kyungmi** [comment]
네 저는 괜찮을것 같습니다.
당장 떠오르는 이름은 'notification-center'나 'notifier', 'server-status-notifier' 정도네요.

**Comment by namenu** [comment]
개발자들을 후킹하려면 왠지 쉽고 단순한 느낌을 줬으면 하는데,
저는 ```simple-notifier``` 추천합니다 ㅎㅎ

여튼, 뷰어팀 내에서 의견 수렴하여 정해주세요!

**Comment by kyungmi** [comment]
아름답지 못한 코드라 전혀 심플과는 거리가 멀지만 저도 `simple-notifier`라는 이름이 좋은 것 같네요.

**Comment by kyungmi** [comment]
변경되었습니다. ㅎㅎ
