### ISSUE TITLE
Title 필드 추가

### ISSUE THREAD

**Issue by freekering** [ridibooks/simple-notifier#31]

**Comment by kyungmi** [comment]
@freekering 
title은 그냥 input[text]로 문자열을 입력받게 하면 될까요?
그리고 원래 있던 content 필드는 optional로 바꾸는게 낫겠죠?

**Comment by freekering** [comment]
네 title은 그냥 input[text]면 되구요
contents 필드는 그냥 놔둬도 될거 같구요. 별개의 이야기인데 contents에 rich text editor를 붙여서 html 을 사용하게 하는건 좀 빡세겠죠?

**Comment by kyungmi** [comment]
@freekering https://facebook.github.io/draft-js/ 이거 한번 붙여볼게요.
