### ISSUE TITLE
paper_lite device type 추가

### ISSUE THREAD

**Issue by freekering** [ridibooks/simple-notifier#39]
페이퍼와 페이퍼 라이트를 구분하기 위해 paper_lite device type을 별도로 추가해야 합니다.
(아직 device type 생성 기능이 없어서...)

**Comment by kyungmi** [comment]
initial data로 추가는 했지만, 실제 DB에 넣어주는 작업도 필요합니다.
제가 직접 데이터를 넣을게요.

**Comment by kyungmi** [comment]
완료했습니다.

**Comment by freekering** [comment]
확인했습니다~
